### PR TITLE
Remade the colorscales

### PR DESCRIPTION
**Pull request by ttislerdg**

### CODE REVIEW

**Comment by ttislerdg** [comment]
Success!

**Comment by ttislerdg** [comment]
Success!

**Comment by ttislerdg** [comment]
Success!

**Comment by ttislerdg** [comment]
Success!

**Comment by ttislerdg** [comment]
Success!

**Comment by ttislerdg** [comment]
Success!

**Comment by ttislerdg** [comment]
Success!

**Comment by ttislerdg** [comment]
Success!

**Comment by ttislerdg** [comment]
Success!

**Comment by ttislerdg** [comment]
Success!

**Comment by ttislerdg** [comment]
Success!

**Comment by djohnson729** [comment]
I got a failure in ColorScaleTest.testLoadXmlTagsEmpty on the value of forceValuesIntoRange. In ColorScale.fromXML, if we want to match the previous logic, forceValuesIntoRange should be false when the value is empty.

**Comment by ttislerdg** [comment]
Success!

**Comment by ttislerdg** [comment]
Success!

**Comment by ttislerdg** [comment]
Success!

**Comment by ttislerdg** [comment]
Success!

**Comment by ttislerdg** [comment]
Success!

**Comment by ttislerdg** [comment]
Success!

**Comment by ttislerdg** [comment]
Success!

**Comment by ttislerdg** [comment]
Success!

**Comment by ttislerdg** [comment]
Success!

**Comment by ttislerdg** [comment]
Success!

**Comment by ttislerdg** [comment]
Success!

**Pull request merged**
