### PR TITLE
CostDistance capability in Spark

### LINKED ISSUE #10: Update cost distance to work with CDH5 and YARN
The current version of MrGeo includes a cost distance operation based on the Giraph graph processing API. Issues with that approach are:
* Problems that arose when porting cost distance for use in CDH5 and YARN
* Giraph required that the entire graph be loaded in memory across the cluster at once, thus making cluster requirements for large-scale cost distance computation prohibitive

To resolve these issues, look into re-implementing the algorithm based on a distributed computing architecture like Apache Spark. The GraphX API included in Apache Spark does not require the entire graph to be memory-based, thus improving scalability, and Spark jobs can run under YARN and coexist nicely with other jobs.

An additional benefit of this effort is having a reusable approach for submitting Spark jobs from MrGeo so that we can take advantage of the simplifying distributed programming paradigm offered by Spark beyond just map/reduce.

### PR DESCRIPTION
**Pull request by djohnson729**
- Closes #10

### CODE REVIEW

**Comment by ttislerdg** [comment]
Test failed with:

Failed tests: 
  CostDistanceMapOpIntegrationTest.testCostDistance:106 Pixel NaN mismatch: px: 222 py: 1242 b: 0 v1: 49997.355 v2: NaN expected:<false> but was:<true>
  CostDistanceMapOpIntegrationTest.testCostDistanceWithBoundsAndLowerZoomLevel:196 Pixel NaN mismatch: px: 370 py: 619 b: 0 v1: 49992.215 v2: NaN expected:<false> but was:<true>
  CostDistanceMapOpIntegrationTest.testCostDistanceWithUniformFriction:144 Pixel NaN mismatch: px: 388 py: 534 b: 0 v1: 19999.266 v2: NaN expected:<false> but was:<true>

**Comment by djohnson729** [comment]
I added a floating point epsilon check in the max cost test.

**Comment by djohnson729** [comment]
I removed a change that I had accidentally pushed.

**Comment by ttislerdg** [comment]
gist with the log debug output:

https://gist.github.com/ttislerdg/a236d15fb2cfad340b5d.js

**Comment by ttislerdg** [comment]
Here's a screenshot of my output

screenshot from 2015-09-17 09_49_49

**Comment by djohnson729** [comment]
After looking at the output from @ttislerdg it was clear that cost distance was not progressing beyond the tile where the start pixel resides. Looking at his debug output as well, I isolated the problem to a serialization issue. I was using Java serialization, and he was using Kryo. I modified the code to remove the specialized Kryo serialization methods so that Kryo will use the Externalizable methods. I verified that this worked on my machine by switching to Kryo serialization.

**Pull request merged**
